<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="forearm_radius" value="0.02" />
    <xacro:property name="forearm_length" value="0.3" />
    <xacro:property name="hand_radius" value="0.02" />
    <xacro:property name="hand_length" value="0.3" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <material name="orange" />
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.5" x="${arm_base_length}" y="${arm_base_width}" z="${arm_base_height}"
                   o_xyz="0 0 ${arm_base_height/2.0}" o_rpy="0 0 0" />
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <material name="yellow" />
            <origin xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${forearm_radius}" l="${forearm_length}"
                   o_xyz="0 0 ${forearm_length/2.0}" o_rpy="0 0 0" />
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
            <material name="orange" />
            <origin xyz="0 0 ${hand_length/2.0}" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
            <origin xyz="0 0 ${hand_length/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${hand_radius}" l="${hand_length}"
                   o_xyz="0 0 ${hand_length/2.0}" o_rpy="0 0 0" />
    </link>

    <joint name="base_arm_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length / 3.0} 0 ${base_height + arm_base_height/2.0}" rpy="0 0 0" />
    </joint>

    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0.0" upper="${pi/2.0}" effort="100.0" velocity="100.0"/>
        <dynamics friction="0.3" damping="0.3" />
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0.0" upper="${pi/2.0}" effort="100.0" velocity="100.0"/>
        <dynamics friction="0.3" damping="0.3" />
    </joint>

</robot>